version: '3'

services:
    db:
        image: postgres
        volumes:
             - ./database:/var/lib/postgresql
    
    migration:
        build: .
        command: python3 manage.py
         migrate
        volumes:
            - .:/usr/src/app
        depends_on:
            - db
    
    web:
        build: .
        command: python3 manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/usr/src/app
        ports:
            - "8000:8000"
        restart: always
        depends_on:
            - db
            - migration