# Generated by Django 2.1.7 on 2019-02-26 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendees',
            name='id_no',
        ),
    ]
